name: Deploy Vue ke Rumahweb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil source code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build Vue
        run: npx vite build
        env:
          DEPLOY_TARGET: rumahweb

      - name: Upload ke Rumahweb
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./dist/
